In [1]:
import numpy as np
arr = np.arange(0,11)

In [2]:
# Get Elem at some index
arr[5]

5

In [3]:
# Get elems in range
arr[1:5]

array([1, 2, 3, 4])

In [6]:
# Brodcasting -> Setting values with range
# Supported By Numpy
arr[0:5] = 105
arr

array([105, 105, 105, 105, 105,   5,   6,   7,   8,   9,  10])

In [7]:
# Reseting array to see binded behaviour
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr_slice = arr[0:5]
arr_slice

array([0, 1, 2, 3, 4])

In [9]:
# Assigned 100 to the arr_slice array.
arr_slice[:] = 100
arr_slice

array([100, 100, 100, 100, 100])

In [10]:
# Numpy does'nt make copies. Because of Massive data.
# First Elements of arr array have been changed by changing arr-slice.
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
# To Make a Copy, arr.copy() has to be used. 
arr_slice = arr[0:5].copy()
arr_slice

array([100, 100, 100, 100, 100])

In [13]:
# Initialising a 2D Array.
arr_2d = np.array(([10,11,12],[13,14,15],[16,17,18]))
arr_2d

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [54]:
# Printing 2D array.
# [row,col]
arr_2d[:2,1:]

array([[11, 12],
       [14, 15]])