In [3]:
import numpy as np

In [4]:
# arrange() returns evely spaced values within an interval.
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [6]:
# zeros() return arrays and matrices of 0.
np.zeros(4)

array([0., 0., 0., 0.])

In [7]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# ones works in similar manner.
np.ones(4)

array([1., 1., 1., 1.])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# linspace() returns evenly spaced numbers over a specified interval.
np.linspace(0,30,4)

array([ 0., 10., 20., 30.])

In [11]:
# eye() returns an Identity Matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
# rand() returns uniform random numbers.
np.random.rand(2)

array([0.36844183, 0.92033079])

In [13]:
np.random.rand(4,4)

array([[0.96134861, 0.11208491, 0.27714186, 0.10995495],
       [0.41103065, 0.12952122, 0.54716891, 0.22466452],
       [0.58942972, 0.66794995, 0.59758777, 0.27465547],
       [0.32970517, 0.68807177, 0.45793782, 0.97650585]])

In [14]:
# randn() returns random numbers from Standard Normal deviation.
np.random.randn(2)

array([-0.46459485, -0.36603645])

In [15]:
# randint() returns between low(inclusive) and high(exclusive)
np.random.randint(1,20,5)

array([ 7,  3,  5, 10, 16])

In [22]:
arr = np.arange(1,21)
rand_arr = np.random.randint(1,30,10)

In [17]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
rand_arr

array([ 7, 13, 20, 18, 14, 26,  7, 25, 24,  1])

In [19]:
# reshape() converts array into a 2d matrix
arr.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [26]:
#max() returns the largest number
rand_arr.max()

26

In [27]:
#argmax() returns the index of the largest number
rand_arr.argmax()

5

In [28]:
# min() returns the smalles number 
# argmin() returns the index of smallest number.
rand_arr.min()

1

In [29]:
rand_arr.argmin()

9